# Generated by Django 3.2.4 on 2021-06-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='nukber',
            new_name='number',
        ),
    ]
